arch:
- aarch64
- amd64
- armhf
- armv7
- i386
codenotary: dev@brenner.tech
description: Use a Cloudflared tunnel (formerly Argo Tunnel) to remotely connect to
  Home Assistant without opening any ports
hassio_api: true
hassio_role: homeassistant
image: ghcr.io/brenner-tobias/cloudflared/{arch}
init: false
map:
- ssl:rw
- share:rw
- config:rw
name: Cloudflared
options:
  additional_hosts: []
  external_hostname: null
  tunnel_name: homeassistant
schema:
  additional_hosts:
  - disableChunkedEncoding: bool?
    hostname: str
    service: str
  catch_all_service: str?
  custom_config: bool?
  data_folder: list(config|share|ssl)?
  external_hostname: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  nginx_proxy_manager: bool?
  quick_tunnel: bool?
  reset_cloudflared_files: bool?
  tunnel_name: str
  warp_enable: bool?
  warp_reset: bool?
  warp_routes:
  - str?
slug: cloudflared
url: https://github.com/brenner-tobias/addon-cloudflared/
version: 1.0.1
